config/routes.rb
Ewebimenik::Application.routes.draw do

  resources :tests, except: [:show] do
    get 'apply' => 'tests#apply_test'
    post 'apply' => 'tests#apply_test_to_pupils', as: 'apply_to_pupils'
    get 'grades'
    resources :tasks, except: [:show]
    get 'pupil_task_points'
    put 'pupil_task_points/:pupil_task_point_id' => 'tests#update_pupil_task_point', as: 'update_pupil_task_point'
  end

  resources :classrooms, except: [:show] do
    resources :pupils, except: [:show]
  end

  devise_for :users

  root to: 'users#index'
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  attr_accessible :name, :user_id

  belongs_to :user
  has_many :pupils

  validates_presence_of :name, :user_id
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  def index
    @classrooms = current_user.classrooms
  end

  def new
    @classroom = current_user.classrooms.new
  end

  def create
    @classroom = current_user.classrooms.new(params[:classroom])
    respond_to do |format|
      if @classroom.save
        format.html { redirect_to new_classroom_path, :notice => "Classroom successfully created."}
        format.js
      else
        format.html { render :action => 'new' }
        format.js
      end
    end
  end

  def edit
    @classroom = current_user.classrooms.find(params[:id])
  end

  def update
    @classroom = current_user.classrooms.find(params[:id])
    if @classroom.update_attributes(params[:classroom])
      redirect_to classrooms_url, :notice  => "Classroom successfully updated."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @classroom = current_user.classrooms.find(params[:id])
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to classrooms_url, :notice => "Classroom successfully destroyom."}
      format.js
    end
  end
end

app/views/classrooms/_classroom.html.haml
%tr{id: "classroom_id_#{classroom.id}"}
  %td= classroom.name
  %td= classroom.pupils.count
  %td= link_to 'Pupils', classroom_pupils_path(classroom)
  %td= link_to 'Edit', edit_classroom_path(classroom)
  %td= link_to 'Destroy', classroom, confirm: "Are you sure you want to delete #{classroom.name}?", method: :delete, remote: true

app/views/classrooms/_form.html.haml
= simple_form_for @classroom, html: {class: 'form-inline'}, remote: remote?(params[:action]) do |f|
  = f.input_field :name, placeholder: 'Name'
  = f.button :submit, class: 'btn'

app/views/classrooms/create.js.erb
<% if @classroom.errors.any? %>

  <% if @classroom.errors[:name].present? %>
    $('#classroom_name').addClass('error').attr("placeholder","<%= @classroom.errors[:name][0] %>").focus();
  <% end %>
<% else %>
  $('#classroom_name').val('').attr("placeholder","Name").removeClass('error').focus();
  $('table').append('<%= j render(@classroom) %>');
<% end %>

app/views/classrooms/destroy.js.erb
$("#classroom_id_<%= @classroom.id %>").remove();

app/views/classrooms/edit.html.haml
%h1 Editing Classroom

= render 'form'

= link_to "View All", classrooms_path

app/views/classrooms/index.html.haml
%h1 Listing classrooms

%table.table
  %tr
    %th Name
    %th Pupil #
    %th
    %th
    %th
  = render @classrooms

%p= link_to "New Classroom", new_classroom_path, id: 'new_classroom_link', remote: true

app/views/classrooms/new.html.haml
%h1 New clasroom

= render 'form'

%p= link_to "Back to List", classrooms_path

app/views/classrooms/new.js.erb
$('#new_classroom_link').hide().after('<%= j render("form") %>');
$('#classroom_name').focus();