config/routes.rb
Ewebimenik::Application.routes.draw do

  resources :tests, except: [:show] do
    get 'apply' => 'tests#apply_test'
    post 'apply' => 'tests#apply_test_to_pupils', as: 'apply_to_pupils'
    get 'grades'
    resources :tasks, except: [:show]
    get 'pupil_task_points'
    put 'pupil_task_points/:pupil_task_point_id' => 'tests#update_pupil_task_point', as: 'update_pupil_task_point'
  end

  resources :classrooms, except: [:show] do
    resources :pupils, except: [:show]
  end

  devise_for :users

  root to: 'users#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :test
  
  attr_accessible :no, :test_id, :max_points

  has_many :pupil_task_points
  has_many :pupils, through: :pupil_task_points
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :load_test

  def index
    @tasks = @test.tasks
  end

  def new
    @task = @test.tasks.new
    unless params[:tasks_count].nil?
      @next_number = params[:tasks_count].to_i + 1
    else
      @next_number = params[:next_number].to_i + 1
    end
  end

  def edit
    @task = @test.tasks.find(params[:id])
  end

  def create
    params[:task][:user_id] = current_user.id
    @task = @test.tasks.new(params[:task])

    if @task.save
      if params[:commit].ends_with? 'Add New'
        redirect_to new_task_path(test_id: params[:task][:test_id], next_number: params[:task][:no]), :notice => "Task successfully created."
      else
        redirect_to tasks_url, notice: 'Task was successfully created.'
      end
    else
      render action: "new"
    end
  end

  def update
    @task = @test.tasks.find(params[:id])

    if @task.update_attributes(params[:task])
      redirect_to tasks_url, notice: 'Task was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @task = @test.tasks.find(params[:id])
    @task.destroy

    redirect_to tasks_url
  end

  def load_test
    @test = current_user.tests.find(params[:test_id])
  end
end

app/views/tasks/_form.html.haml
= simple_form_for([@test, @task]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :no, input_html: { value: @next_number }
    = f.association :test, selected: @test_id
    = f.input :max_points, autofocus: true

    = f.button :submit, 'Create Task And Add New', class: 'btn'
    = f.button :submit, class: 'btn'

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Back', test_tasks_path(@test)

app/views/tasks/index.html.haml
%h1 Listing tasks for test #{@test.name}

%table.table
  %tr
    %th No
    %th Max Points
    %th
    %th

  - @tasks.each do |task|
    %tr
      %td= task.no
      %td= task.max_points
      %td= link_to 'Edit', edit_test_task_path(@test,task)
      %td= link_to 'Destroy', [@test,task], method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Task', new_test_task_path(@test)

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', test_tasks_path(@test)