config/routes.rb
Ewebimenik::Application.routes.draw do

  resources :tests, except: [:show] do
    get 'apply' => 'tests#apply_test'
    post 'apply' => 'tests#apply_test_to_pupils', as: 'apply_to_pupils'
    get 'grades'
    resources :tasks, except: [:show]
    get 'pupil_task_points'
    put 'pupil_task_points/:pupil_task_point_id' => 'tests#update_pupil_task_point', as: 'update_pupil_task_point'
  end

  resources :classrooms, except: [:show] do
    resources :pupils, except: [:show]
  end

  devise_for :users

  root to: 'users#index'
end

app/models/pupil.rb
class Pupil < ActiveRecord::Base
  belongs_to :classroom
  belongs_to :user
  attr_accessible :first_name, :last_name, :classroom_id, :user_id
  has_many :pupil_task_points
  has_many :tasks, through: :pupil_task_points

  validates_presence_of :first_name, :last_name

  def full_name
    first_name + ' ' + last_name
  end
end

app/controllers/pupils_controller.rb
class PupilsController < ApplicationController

  before_filter :load_classroom

  def index
    @pupils = @classroom.pupils
  end

  def new
    @pupil = @classroom.pupils.new
  end

  def edit
    @pupil = @classroom.pupils.find(params[:id])
  end

  def create
    @pupil = @classroom.pupils.new(params[:pupil])

    respond_to do |format|
      if @pupil.save
        format.html { redirect_to new_classroom_pupil_url(@classroom), :notice => "Pupil successfully created." }
        format.js
      else
        format.html { render action: "new" }
        format.js { }
      end
    end
  end

  def update
    @pupil = @classroom.pupils.find(params[:id])

    if @pupil.update_attributes(params[:pupil])
      redirect_to classroom_pupils_url, notice: 'Pupil was successfully updated.' 
    else
      render action: "edit" 
    end
  end

  def destroy
    @pupil = @classroom.pupils.find(params[:id])
    @pupil.destroy
    respond_to do |format|
      format.html { redirect_to classroom_pupils_url }
      format.js
    end
  end

  def load_classroom
    @classroom = current_user.classrooms.find(params[:classroom_id])
  end
end

app/views/pupils/_form.html.haml
= simple_form_for [@classroom,@pupil], html: {class: "form-inline"}, remote: true do |f|
  .errors
  
  = f.input_field :first_name, placeholder: 'First name'
  = f.input_field :last_name, placeholder: 'Last Name'

  = f.button :submit

app/views/pupils/_form_edit.html.haml
= simple_form_for [@classroom,@pupil], html: {class: "form-horizontal"} do |f|

  .form-inputs
    = f.input :first_name, placeholder: 'First name'
    = f.input :last_name, placeholder: 'Last Name'

  .form-actions
    = f.button :submit, class: 'btn-primary'

app/views/pupils/_pupil.html.haml
%tr{id: "pupil_id_#{pupil.id}"}
  %td= pupil.first_name
  %td= pupil.last_name
  %td= link_to 'Edit', edit_classroom_pupil_path(@classroom,pupil)
  %td= link_to 'Destroy', [@classroom, pupil], confirm: "Are you sure you want to delete #{pupil.full_name}?", method: :delete, remote: true

app/views/pupils/create.js.erb
<% if @pupil.errors.any? %>

  <% if @pupil.errors[:last_name].present? %>
    $('#pupil_last_name').addClass('error').attr("placeholder","<%= @pupil.errors[:last_name][0] %>").focus();
  <% end %>
  <% if @pupil.errors[:first_name].present? %>
    $('#pupil_first_name').addClass('error').attr("placeholder","<%= @pupil.errors[:first_name][0] %>").focus();
  <% end %>
<% else %>
  $('#pupil_last_name').val('').attr("placeholder","Last name").removeClass('error');
  $('#pupil_first_name').val('').attr("placeholder","First name").removeClass('error').focus();
  $('table').append('<%= j render(@pupil) %>');
<% end %>

app/views/pupils/destroy.js.erb
$("#pupil_id_<%= @pupil.id %>").remove();

app/views/pupils/edit.html.haml
%h1 Editing pupil

= render 'form_edit'

= link_to 'Back', classroom_pupils_path(@classroom)

app/views/pupils/index.html.haml
%h1 Listing pupils for classroom #{@classroom.name}

%table.table
  %tr
    %th First name
    %th Last name
    %th
    %th
    %th

  = render @pupils

%br

= link_to 'New Pupil', new_classroom_pupil_path(@classroom), id: "new_pupil_link", remote: true

app/views/pupils/new.html.haml
%h1 New pupil

= render 'form'

= link_to 'Back', classroom_pupils_path(@classroom)

app/views/pupils/new.js.erb
$('#new_pupil_link').hide().after('<%= j render("form") %>');
$('#pupil_first_name').focus();
$('input.btn').bind("ajax:error", function(event,data,status,xhr) { alert('Error!');});