config/routes.rb
Ewebimenik::Application.routes.draw do

  resources :tests, except: [:show] do
    get 'apply' => 'tests#apply_test'
    post 'apply' => 'tests#apply_test_to_pupils', as: 'apply_to_pupils'
    get 'grades'
    resources :tasks, except: [:show]
    get 'pupil_task_points'
    put 'pupil_task_points/:pupil_task_point_id' => 'tests#update_pupil_task_point', as: 'update_pupil_task_point'
  end

  resources :classrooms, except: [:show] do
    resources :pupils, except: [:show]
  end

  devise_for :users

  root to: 'users#index'
end

app/views/layouts/_navigation.html.haml
= link_to "Home", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Classrooms', classrooms_path
    %li
      = link_to 'Tests', tests_path
    / %li
    /   = link_to 'Tasks', tasks_path
    / %li
    /   = link_to 'Pupil Task Points', pupil_task_points_path
    / %li
    /   = link_to 'Grades', grades_path
    %li
      = link_to('Logout', destroy_user_session_path, :method=>'delete')
  - else
    %li
      = link_to('Login', new_user_session_path)
  - if user_signed_in?
    %li
      = link_to('Edit account', edit_user_registration_path)
  - else
    %li
      = link_to('Sign up', new_user_registration_path)

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title Ewebimenik
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = bootstrap_flash
              = yield